# Generated by Django 4.2.7 on 2023-11-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria', '0002_cliente_remove_todolist_category_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_padaria.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_padaria.pedidos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_padaria.produto')),
            ],
        ),
    ]
